const images = {
  "Красные сорта: расширяем горизонты": "https://login.inboxer.pro/app/public/file/view/12a/2goe",
  "Вино и сыр": "https://login.inboxer.pro/app/public/file/view/12a/2fg9",
  "Виноделие Франции": "https://login.inboxer.pro/app/public/file/view/12a/2fgb",
  "Виноделие Италии": "https://login.inboxer.pro/app/public/file/view/12a/2fge",
  "Виноделие Испании": "https://login.inboxer.pro/app/public/file/view/12a/2fpm",
  "Виноделие Южной и Северной Америки": "https://login.inboxer.pro/app/public/file/view/12a/2fpl",
  "Виноделие Кавказа: Грузия и Армения": "https://login.inboxer.pro/app/public/file/view/12a/2hms",
  "Аперитив или дижестив?": "https://login.inboxer.pro/app/public/file/view/12a/2hmu",
  "Шампанское без исключений": "https://login.inboxer.pro/app/public/file/view/12a/2hmt",
  "Вина России и мира": "https://login.inboxer.pro/app/public/file/view/12a/2igr",
  "Виноделие Германии": "https://login.inboxer.pro/app/public/file/view/12a/2fgc",
  "Виноделие России": "https://login.inboxer.pro/app/public/file/view/12a/2g0n",
  "Виноделие Австрии": "https://login.inboxer.pro/app/public/file/view/12a/2i5v",
  "Все оттенки розе": "https://login.inboxer.pro/app/public/file/view/12a/2g0m",
  "Винные тренды": "https://login.inboxer.pro/app/public/file/view/12a/2i5w",
  "Хиты Нового Света": "https://login.inboxer.pro/app/public/file/view/12a/2i5y",
  "Винная интуиция": "https://login.inboxer.pro/app/public/file/view/12a/2i5z",
  Виноджинариум: "https://login.inboxer.pro/app/public/file/view/12a/2ot1",
  "Яркие белые: ароматические сорта винограда": "https://login.inboxer.pro/app/public/file/view/12a/2g0l",
  "Яркие белые": "https://login.inboxer.pro/app/public/file/view/12a/2g0l",
  "Хиты Нового Света: от мальбека до шираза": "https://login.inboxer.pro/app/public/file/view/12a/2g0j",
  "Хиты Нового Света. New Edition": "https://login.inboxer.pro/app/public/file/view/12a/2g0j",
  "Wine pairing: вино и еда": "https://login.inboxer.pro/app/public/file/view/12a/2g0k",
  "Двойной стандарт": "https://login.inboxer.pro/app/public/file/view/12a/2fga",
  "Двойной стандарт: шардоне и пино гриджо": "https://login.inboxer.pro/app/public/file/view/12a/2fga",
  "Колесо ароматов": "https://login.inboxer.pro/app/public/file/view/12a/2fgd",
  "Колесо ароматов. Фруктовая симфония": "https://login.inboxer.pro/app/public/file/view/12a/2fgd",
  "Колесо ароматов. Ягодная гамма": "https://login.inboxer.pro/app/public/file/view/12a/2n49",
  "Wine. Naked": "https://login.inboxer.pro/app/public/file/view/12a/2fgf",
  "Игристые вина мира": "https://login.inboxer.pro/app/public/file/view/12a/2fgg",
  "WineState Experience": "https://login.inboxer.pro/app/public/file/view/12a/2fgh",
  "WineState Experience «Кругосветное путешествие»": "https://login.inboxer.pro/app/public/file/view/12a/2fgh",
  "WineState Experience «Сырная симфония»": "https://login.inboxer.pro/app/public/file/view/12a/2fgh",
  "Вино за 3 дня. New Edition": "https://login.inboxer.pro/app/public/file/view/12a/2fgt",
  "Такой разный совиньон блан": "https://login.inboxer.pro/app/public/file/view/12a/2fgk",
  "Коньяк, арманьяк и другие стили бренди": "https://login.inboxer.pro/app/public/file/view/12a/2fgu",
  "Виноделие Кавказа": "https://login.inboxer.pro/app/public/file/view/12a/2fgv",
  "Винное казино": "https://login.inboxer.pro/app/public/file/view/12a/2jjr",
  "Лекция #2. Фруктовая симфония": "https://login.inboxer.pro/app/public/file/view/12a/2g8y",
  "Этюд пряностей": "https://login.inboxer.pro/app/public/file/view/12a/2g8z",
  "Ягодная гамма": "https://login.inboxer.pro/app/public/file/view/12a/2g8x",
  "Игра контрастов: каберне совиньон и пино нуар": "https://login.inboxer.pro/app/public/file/view/12a/2g91",
  "Игра контрастов": "https://login.inboxer.pro/app/public/file/view/12a/2g91",
  "Работаем с вином. Intermediate Level. Практика": "https://login.inboxer.pro/app/public/file/view/12a/2lky",
  "Работаем с вином. Intermediate Level. Теория": "https://login.inboxer.pro/app/public/file/view/12a/2lkx",
  "Другие красные": "https://login.inboxer.pro/app/public/file/view/12a/2mc3",
  Виноджинариум: "https://login.inboxer.pro/app/public/file/view/12a/2pk2",
  "Виноделие Средиземноморья": "https://login.inboxer.pro/app/public/file/view/12a/2qkv",
};

export default images;
